"""Version10 - add col probeninformation_ltx to vorlaufige proben

Revision ID: 1260575e3ebf
Revises: 9dc9c61a6237
Create Date: 2025-12-05 08:46:25.099599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1260575e3ebf'
down_revision: Union[str, None] = '9dc9c61a6237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vorlaeufigeproben', sa.Column('probeninformation_ltx', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vorlaeufigeproben', 'probeninformation_ltx', ['probeninformation_ltx'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vorlaeufigeproben', type_='foreignkey')
    op.drop_column('vorlaeufigeproben', 'probeninformation_ltx')
    # ### end Alembic commands ###
