"""Version4 - EDTA Proben

Revision ID: 14e4fd61d0b4
Revises: b131a8e7bbf2
Create Date: 2025-12-02 10:25:53.157600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '14e4fd61d0b4'
down_revision: Union[str, None] = 'b131a8e7bbf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edtaplasma',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('probeninformation_ltx', sa.Integer(), nullable=True),
    sa.Column('differenzierungsmerkmal', mysql.TINYINT(), nullable=True),
    sa.Column('boxnummer', sa.Integer(), nullable=True),
    sa.Column('boxzeile', mysql.TEXT(), nullable=True),
    sa.Column('boxspalte', sa.Integer(), nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', sa.Integer(), server_default='0', nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['differenzierungsmerkmal'], ['differenzierungsmerkmal_serum.id'], ),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], ),
    sa.ForeignKeyConstraint(['probeninformation_ltx'], ['probeninformation_ltx.id'], ),
    sa.ForeignKeyConstraint(['status'], ['status.id'], ),
    sa.PrimaryKeyConstraint('barcode_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edtaplasma')
    # ### end Alembic commands ###
