"""Version16 - col remove stuhlproben

Revision ID: 17a3fb9779a2
Revises: 2d56c8eee576
Create Date: 2026-01-30 08:02:13.371163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '17a3fb9779a2'
down_revision: Union[str, None] = '2d56c8eee576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'stuhlproben_ibfk_2',
        'stuhlproben',
        type_='foreignkey'
    )
    op.drop_table('differenzierungsmerkmal_stuhl')


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'differenzierungsmerkmal_stuhl',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(length=255), nullable=False),
    )

    op.create_foreign_key(
        'stuhlproben_ibfk_2',
        'stuhlproben',
        'differenzierungsmerkmal_stuhl',
        ['differenzierungsmerkmal'],
        ['id']
    )

    # ### end Alembic commands ###
