"""Version6 - rename Edtaplasmaproben

Revision ID: 1fab6be05671
Revises: 2a33ed942c6e
Create Date: 2025-12-02 15:28:31.088447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1fab6be05671'
down_revision: Union[str, None] = '2a33ed942c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edtaplasmaproben',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('probeninformation_ltx', sa.Integer(), nullable=True),
    sa.Column('differenzierungsmerkmal', mysql.TINYINT(), nullable=True),
    sa.Column('boxnummer', sa.Integer(), nullable=True),
    sa.Column('boxzeile', mysql.TEXT(), nullable=True),
    sa.Column('boxspalte', sa.Integer(), nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', sa.Integer(), server_default='0', nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['differenzierungsmerkmal'], ['differenzierungsmerkmal_serum.id'], ),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], ),
    sa.ForeignKeyConstraint(['probeninformation_ltx'], ['probeninformation_ltx.id'], ),
    sa.ForeignKeyConstraint(['status'], ['status.id'], ),
    sa.PrimaryKeyConstraint('barcode_id')
    )
    op.drop_table('edtaplasma')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edtaplasma',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('probeninformation_ltx', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('differenzierungsmerkmal', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('boxnummer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('boxzeile', mysql.TEXT(), nullable=True),
    sa.Column('boxspalte', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['differenzierungsmerkmal'], ['differenzierungsmerkmal_serum.id'], name='edtaplasma_ibfk_1'),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], name='edtaplasma_ibfk_2'),
    sa.ForeignKeyConstraint(['probeninformation_ltx'], ['probeninformation_ltx.id'], name='edtaplasma_ibfk_3'),
    sa.ForeignKeyConstraint(['status'], ['status.id'], name='edtaplasma_ibfk_4'),
    sa.PrimaryKeyConstraint('barcode_id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.drop_table('edtaplasmaproben')
    # ### end Alembic commands ###
