"""Version5 - patient fallnummer

Revision ID: 2a33ed942c6e
Revises: 14e4fd61d0b4
Create Date: 2025-12-02 10:34:49.756836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a33ed942c6e'
down_revision: Union[str, None] = '14e4fd61d0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('sap_fallnummer', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'sap_fallnummer')
    # ### end Alembic commands ###
