"""Version15 - col stuhlproben

Revision ID: 2d56c8eee576
Revises: 7c136cc92f5c
Create Date: 2026-01-29 14:32:34.145840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d56c8eee576'
down_revision: Union[str, None] = '7c136cc92f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stuhlproben', 'barcode_id')
    op.add_column('stuhlproben', sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False))
    op.create_foreign_key(None, 'stuhlproben', 'differenzierungsmerkmal_stuhl', ['differenzierungsmerkmal'], ['id'])
    op.create_foreign_key(None, 'stuhlproben', 'patient', ['patient_Id_intern'], ['patient_Id_intern'])
    op.create_foreign_key(None, 'stuhlproben', 'status', ['status'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stuhlproben', type_='foreignkey')
    op.drop_constraint(None, 'stuhlproben', type_='foreignkey')
    op.drop_constraint(None, 'stuhlproben', type_='foreignkey')
    op.drop_column('stuhlproben', 'barcode_id')
    # ### end Alembic commands ###
