"""Version8 - change stuhlproben

Revision ID: 572ce1717b14
Revises: cb3493f2ccd7
Create Date: 2025-12-04 09:11:19.495349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '572ce1717b14'
down_revision: Union[str, None] = 'cb3493f2ccd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stuhlproben', sa.Column('barcode_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('stuhlproben', sa.Column('probeninformation_ltx', sa.Integer(), nullable=True))
    op.add_column('stuhlproben', sa.Column('boxnummer', sa.Integer(), nullable=True))
    op.add_column('stuhlproben', sa.Column('boxzeile', mysql.TEXT(), nullable=True))
    op.add_column('stuhlproben', sa.Column('boxspalte', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stuhlproben', 'probeninformation_ltx', ['probeninformation_ltx'], ['id'])
    op.drop_column('stuhlproben', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stuhlproben', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'stuhlproben', type_='foreignkey')
    op.drop_column('stuhlproben', 'boxspalte')
    op.drop_column('stuhlproben', 'boxzeile')
    op.drop_column('stuhlproben', 'boxnummer')
    op.drop_column('stuhlproben', 'probeninformation_ltx')
    op.drop_column('stuhlproben', 'barcode_id')
    # ### end Alembic commands ###
