"""Version14 - constraint differnzierungsmerkmal galle

Revision ID: 7c136cc92f5c
Revises: 8b4eafea3166
Create Date: 2026-01-28 14:08:48.283752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c136cc92f5c'
down_revision: Union[str, None] = '8b4eafea3166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'galleproben',
        sa.Column('differenzierungsmerkmal', mysql.TINYINT(), nullable=True)
    )

    op.create_foreign_key(
        'fk_galleproben_differenzierungsmerkmal',
        'galleproben',
        'differenzierungsmerkmal_galle',
        ['differenzierungsmerkmal'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_galleproben_differenzierungsmerkmal',
        'galleproben',
        type_='foreignkey'
    )

    op.drop_column(
        'galleproben',
        'differenzierungsmerkmal'
    )

    # ### end Alembic commands ###
