"""Version13 - differnzierungsmerkmal galle

Revision ID: 8b4eafea3166
Revises: fbbb145040eb
Create Date: 2026-01-28 13:27:10.889687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b4eafea3166'
down_revision: Union[str, None] = 'fbbb145040eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('differenzierungsmerkmal_galle',
    sa.Column('id', mysql.TINYINT(display_width=4), autoincrement=True, nullable=False),
    sa.Column('differenzierungsmerkmal_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('differenzierungsmerkmal_galle')
    # ### end Alembic commands ###
