"""initial setup

Revision ID: 9a8320022dcb
Revises: 
Create Date: 2025-11-17 15:38:54.839793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a8320022dcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paraffinproben',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('uebergeordnete_probenart', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('untergeordnete_probenart', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], name='paraffinproben_ibfk_1'),
    sa.ForeignKeyConstraint(['status'], ['status.id'], name='paraffinproben_ibfk_4'),
    sa.ForeignKeyConstraint(['uebergeordnete_probenart'], ['uebergeordnete_probenart_paraffin.id'], name='paraffinproben_ibfk_2'),
    sa.ForeignKeyConstraint(['untergeordnete_probenart'], ['untergeordnete_probenart_paraffin.id'], name='paraffinproben_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
