"""Version9 - add col in stuhlproben table

Revision ID: 9dc9c61a6237
Revises: 572ce1717b14
Create Date: 2025-12-04 10:51:15.766232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc9c61a6237'
down_revision: Union[str, None] = '572ce1717b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stuhlproben', sa.Column('anzahl_statuswechsel', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stuhlproben', 'anzahl_statuswechsel')
    # ### end Alembic commands ###
