"""Version17 - stuhlproben pk

Revision ID: 9fcf5b33fd4d
Revises: 17a3fb9779a2
Create Date: 2026-01-30 08:22:57.617738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9fcf5b33fd4d'
down_revision: Union[str, None] = '17a3fb9779a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key(
        'pk_stuhlproben',
        'stuhlproben',
        ['barcode_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'pk_stuhlproben',
        'stuhlproben',
        type_='primary'
    )
    # ### end Alembic commands ###
