"""Version11 - add table differenzierungsmerkmal_edtaplasma

Revision ID: af50266a3ccc
Revises: 1260575e3ebf
Create Date: 2025-12-09 11:11:14.729694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af50266a3ccc'
down_revision: Union[str, None] = '1260575e3ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('differenzierungsmerkmal_edtaplasma',
    sa.Column('id', mysql.TINYINT(display_width=4), autoincrement=True, nullable=False),
    sa.Column('differenzierungsmerkmal_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('differenzierungsmerkmal_edtaplasma')
    # ### end Alembic commands ###