"""Version3 - galleproben

Revision ID: b131a8e7bbf2
Revises: bece8dc53682
Create Date: 2025-12-01 14:36:10.068906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b131a8e7bbf2'
down_revision: Union[str, None] = 'bece8dc53682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probeninformation_ltx', 
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('probeninformation_text', mysql.TEXT(), nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    
    op.create_table('galleproben',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('probeninformation_ltx', sa.Integer(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('boxnummer', sa.Integer(), nullable=True),
    sa.Column('boxzeile', mysql.TEXT(), nullable=True),
    sa.Column('boxspalte', sa.Integer(), nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', sa.Integer(), server_default='0', nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], ),
    sa.ForeignKeyConstraint(['probeninformation_ltx'], ['probeninformation_ltx.id'], ),
    sa.ForeignKeyConstraint(['status'], ['status.id'], ),
    sa.PrimaryKeyConstraint('barcode_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_foreign_key(None, 'stuhlproben', 'differenzierungsmerkmal_stuhl', ['differenzierungsmerkmal'], ['id'])
    op.create_foreign_key(None, 'stuhlproben', 'patient', ['patient_Id_intern'], ['patient_Id_intern'])
    op.create_foreign_key(None, 'stuhlproben', 'status', ['status'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stuhlproben', type_='foreignkey')
    op.drop_constraint(None, 'stuhlproben', type_='foreignkey')
    op.drop_constraint(None, 'stuhlproben', type_='foreignkey')
    op.drop_table('galleproben')
    op.drop_table('probeninformation_ltx')
    # ### end Alembic commands ###
