"""Version18 - gewebeproben new item

Revision ID: c8a087be60c4
Revises: 9fcf5b33fd4d
Create Date: 2026-05-18 13:29:45.978060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c8a087be60c4'
down_revision: Union[str, None] = '9fcf5b33fd4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gewebeproben', sa.Column('uhrzeit_probennahme', mysql.TEXT(), nullable=True))
    op.add_column('gewebeproben', sa.Column('uhrzeit_freeze', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gewebeproben', 'uhrzeit_freeze')
    op.drop_column('gewebeproben', 'uhrzeit_probennahme')
    # ### end Alembic commands ###
