"""Version7 - add col to stuhlproben

Revision ID: cb3493f2ccd7
Revises: 1fab6be05671
Create Date: 2025-12-02 16:11:40.717235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb3493f2ccd7'
down_revision: Union[str, None] = '1fab6be05671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stuhlproben', sa.Column('lagerraum', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stuhlproben', 'lagerraum')
    # ### end Alembic commands ###
