"""Version19 - paraffinproben new item

Revision ID: d23ddf398377
Revises: c8a087be60c4
Create Date: 2026-05-19 12:42:18.092121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd23ddf398377'
down_revision: Union[str, None] = 'c8a087be60c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paraffinproben', sa.Column('uhrzeit_probennahme', mysql.TEXT(), nullable=True))
    op.add_column('paraffinproben', sa.Column('uhrzeit_freeze', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paraffinproben', 'uhrzeit_freeze')
    op.drop_column('paraffinproben', 'uhrzeit_probennahme')
    # ### end Alembic commands ###
