"""Version1

Revision ID: d4fcb40778b6
Revises: 1ce075381220
Create Date: 2025-11-25 11:32:02.056123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fcb40778b6'
down_revision: Union[str, None] = '1ce075381220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gewebeproben', sa.Column('anzahl_statuswechsel', sa.Integer(), nullable=True))
    op.add_column('serumproben', sa.Column('anzahl_statuswechsel', sa.Integer(), nullable=True))
    op.add_column('urinproben', sa.Column('anzahl_statuswechsel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urinproben', 'anzahl_statuswechsel')
    op.drop_column('serumproben', 'anzahl_statuswechsel')
    op.drop_column('gewebeproben', 'anzahl_statuswechsel')
    # ### end Alembic commands ###
