"""msg

Revision ID: e215f5135e16
Revises: d1bb46924aec
Create Date: 2025-11-25 10:12:53.326543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e215f5135e16'
down_revision: Union[str, None] = 'd1bb46924aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('differenzierungsmerkmal_serum',
    sa.Column('id', mysql.TINYINT(), autoincrement=True, nullable=False),
    sa.Column('differenzierungsmerkmal_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('probenabholer',
    sa.Column('id', mysql.TINYINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('probenquelle_urin',
    sa.Column('id', mysql.TINYINT(), autoincrement=True, nullable=False),
    sa.Column('probenquelle_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('untergeordnete_probenart_paraffin',
    sa.Column('id', mysql.TINYINT(), autoincrement=True, nullable=False),
    sa.Column('untergeordnete_probenart_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gewebeproben',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('differenzierungsmerkmal', mysql.TINYINT(), nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('probeninformation', sa.Integer(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('boxnummer', sa.Integer(), nullable=True),
    sa.Column('boxzeile', mysql.TEXT(), nullable=True),
    sa.Column('boxspalte', sa.Integer(), nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['differenzierungsmerkmal'], ['differenzierungsmerkmal_gewebe.id'], ),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], ),
    sa.ForeignKeyConstraint(['probeninformation'], ['probeninformation.id'], ),
    sa.ForeignKeyConstraint(['status'], ['status.id'], ),
    sa.PrimaryKeyConstraint('barcode_id')
    )
    op.create_table('paraffinproben',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('uebergeordnete_probenart', mysql.TINYINT(), nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('untergeordnete_probenart', mysql.TINYINT(), nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], ),
    sa.ForeignKeyConstraint(['status'], ['status.id'], ),
    sa.ForeignKeyConstraint(['uebergeordnete_probenart'], ['uebergeordnete_probenart_paraffin.id'], ),
    sa.ForeignKeyConstraint(['untergeordnete_probenart'], ['untergeordnete_probenart_paraffin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serumproben',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('probeninformation', sa.Integer(), nullable=True),
    sa.Column('differenzierungsmerkmal', mysql.TINYINT(), nullable=True),
    sa.Column('boxnummer', sa.Integer(), nullable=True),
    sa.Column('boxzeile', mysql.TEXT(), nullable=True),
    sa.Column('boxspalte', sa.Integer(), nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['differenzierungsmerkmal'], ['differenzierungsmerkmal_serum.id'], ),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], ),
    sa.ForeignKeyConstraint(['probeninformation'], ['probeninformation.id'], ),
    sa.ForeignKeyConstraint(['status'], ['status.id'], ),
    sa.PrimaryKeyConstraint('barcode_id')
    )
    op.create_table('vorlaeufigeproben',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('probeninformation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], ),
    sa.ForeignKeyConstraint(['probeninformation'], ['probeninformation.id'], ),
    sa.PrimaryKeyConstraint('barcode_id')
    )
    op.add_column('urinproben', sa.Column('anzahl_statuswechsel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urinproben', 'anzahl_statuswechsel')
    op.drop_table('vorlaeufigeproben')
    op.drop_table('serumproben')
    op.drop_table('paraffinproben')
    op.drop_table('gewebeproben')
    op.drop_table('untergeordnete_probenart_paraffin')
    op.drop_table('probenquelle_urin')
    op.drop_table('probenabholer')
    op.drop_table('differenzierungsmerkmal_serum')
    # ### end Alembic commands ###
