"""Version12 - new table ltx_fragebogen and lookup table

Revision ID: fbbb145040eb
Revises: af50266a3ccc
Create Date: 2026-01-21 10:08:37.118199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fbbb145040eb'
down_revision: Union[str, None] = 'af50266a3ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ltx_fragebogen_ernaerung_lookup',
    sa.Column('id', mysql.TINYINT(), autoincrement=True, nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ltx_fragebogen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('geschlecht', mysql.TEXT(), nullable=True),
    sa.Column('alter', sa.Integer(), nullable=True),
    sa.Column('gewicht', sa.Integer(), nullable=True),
    sa.Column('groesse', sa.Integer(), nullable=True),
    sa.Column('beruf', mysql.TEXT(), nullable=True),
    sa.Column('kinder_anzahl', sa.Integer(), nullable=True),
    sa.Column('krankenversicherung', mysql.TEXT(), nullable=True),
    sa.Column('epices_score', sa.Integer(), nullable=True),
    sa.Column('sozialer_prekaritaetsindex', sa.Integer(), nullable=True),
    sa.Column('bewegung', mysql.TEXT(), nullable=True),
    sa.Column('rotes_fleisch', mysql.TINYINT(), nullable=True),
    sa.Column('rotes_fleisch_anz', sa.Integer(), nullable=True),
    sa.Column('gefluegel', mysql.TINYINT(), nullable=True),
    sa.Column('gefluegel_anz', sa.Integer(), nullable=True),
    sa.Column('verarbeitetes_fleisch', mysql.TINYINT(), nullable=True),
    sa.Column('verarbeitetes_fleisch_anz', sa.Integer(), nullable=True),
    sa.Column('fisch_meeresfruechte', mysql.TINYINT(), nullable=True),
    sa.Column('fisch_meeresfruechte_anz', sa.Integer(), nullable=True),
    sa.Column('eier', mysql.TINYINT(), nullable=True),
    sa.Column('eier_anz', sa.Integer(), nullable=True),
    sa.Column('fruechte_gemuese', mysql.TINYINT(), nullable=True),
    sa.Column('fruechte_gemuese_anz', sa.Integer(), nullable=True),
    sa.Column('staerkehaltige_lebensmittel', mysql.TINYINT(), nullable=True),
    sa.Column('staerkehaltige_lebensmittel_anz', sa.Integer(), nullable=True),
    sa.Column('vollwertkost', mysql.TINYINT(), nullable=True),
    sa.Column('vollwertkost_anz', sa.Integer(), nullable=True),
    sa.Column('huelsenfruechte', mysql.TINYINT(), nullable=True),
    sa.Column('huelsenfruechte_anz', sa.Integer(), nullable=True),
    sa.Column('joghurt', mysql.TINYINT(), nullable=True),
    sa.Column('joghurt_anz', sa.Integer(), nullable=True),
    sa.Column('kaese', mysql.TINYINT(), nullable=True),
    sa.Column('kaese_anz', sa.Integer(), nullable=True),
    sa.Column('milch', mysql.TINYINT(), nullable=True),
    sa.Column('milch_anz', sa.Integer(), nullable=True),
    sa.Column('fruehstueckscerealien', mysql.TINYINT(), nullable=True),
    sa.Column('fruehstueckscerealien_anz', sa.Integer(), nullable=True),
    sa.Column('fettfreie_zuckerhaltige_produkte', mysql.TINYINT(), nullable=True),
    sa.Column('fettfreie_zuckerhaltige_produkte_anz', sa.Integer(), nullable=True),
    sa.Column('fetthaltige_zuckerhaltige_produkte', mysql.TINYINT(), nullable=True),
    sa.Column('fetthaltige_zuckerhaltige_produkte_anz', sa.Integer(), nullable=True),
    sa.Column('fettige_salzige_produkte', mysql.TINYINT(), nullable=True),
    sa.Column('fettige_salzige_produkte_anz', sa.Integer(), nullable=True),
    sa.Column('fette', mysql.TINYINT(), nullable=True),
    sa.Column('fette_anz', sa.Integer(), nullable=True),
    sa.Column('zuckerhaltige_getraenke', mysql.TINYINT(), nullable=True),
    sa.Column('zuckerhaltige_getraenke_anz', sa.Integer(), nullable=True),
    sa.Column('wein', mysql.TINYINT(), nullable=True),
    sa.Column('wein_anz', sa.Integer(), nullable=True),
    sa.Column('bier', mysql.TINYINT(), nullable=True),
    sa.Column('bier_anz', sa.Integer(), nullable=True),
    sa.Column('aperitifs_digestifs', mysql.TINYINT(), nullable=True),
    sa.Column('aperitifs_digestifs_anz', sa.Integer(), nullable=True),
    sa.Column('nierenfunktion', mysql.TEXT(), nullable=True),
    sa.Column('diabetes', mysql.TEXT(), nullable=True),
    sa.Column('immunsuppression_immunkompetent', mysql.TINYINT(), nullable=True),
    sa.Column('immunsuppression_HIV_AIDS', mysql.TINYINT(), nullable=True),
    sa.Column('immunsuppression_solider_krebs', mysql.TINYINT(), nullable=True),
    sa.Column('immunsuppression_maligne_heamatopathie', mysql.TINYINT(), nullable=True),
    sa.Column('immunsuppression_organ_knochenmarkstransplantation', mysql.TINYINT(), nullable=True),
    sa.Column('immunsuppression_neutropenie', mysql.TINYINT(), nullable=True),
    sa.Column('immunsuppression_angeborene_immunschwaeche', mysql.TINYINT(), nullable=True),
    sa.Column('immunsuppression_immunsuppessive_therapie', mysql.TINYINT(), nullable=True),
    sa.Column('multiresistenz_infektion', mysql.TEXT(), nullable=True),
    sa.Column('antibiotische_behandlung', mysql.TEXT(), nullable=True),
    sa.Column('antibiotische_therapie_1_name', mysql.TEXT(), nullable=True),
    sa.Column('antibiotische_therapie_1_zeitraum', mysql.TEXT(), nullable=True),
    sa.Column('antibiotische_therapie_1_grund', mysql.TEXT(), nullable=True),
    sa.Column('antibiotische_therapie_2_name', mysql.TEXT(), nullable=True),
    sa.Column('antibiotische_therapie_2_zeitraum', mysql.TEXT(), nullable=True),
    sa.Column('antibiotische_therapie_2_grund', mysql.TEXT(), nullable=True),
    sa.Column('antibiotische_therapie_3_name', mysql.TEXT(), nullable=True),
    sa.Column('antibiotische_therapie_3_zeitraum', mysql.TEXT(), nullable=True),
    sa.Column('antibiotische_therapie_3_grund', mysql.TEXT(), nullable=True),
    sa.Column('langzeit_norfloxacin_prophylaxe', mysql.TEXT(), nullable=True),
    sa.Column('hospitalisation_vergangenes_jahr', mysql.TEXT(), nullable=True),
    sa.Column('geburtsort_ausserhalb_deutschlands', mysql.TEXT(), nullable=True),
    sa.Column('geburtsort_ausserhalb_deutschlands_ort', mysql.TEXT(), nullable=True),
    sa.Column('auslandsreise_letzte_drei_monate', mysql.TEXT(), nullable=True),
    sa.Column('auslandsreise_letzte_drei_monate_ort', mysql.TEXT(), nullable=True),
    sa.Column('auslandsreise_antibiotika', mysql.TEXT(), nullable=True),
    sa.Column('auslandsreise_durchfall', mysql.TEXT(), nullable=True),
    sa.Column('auslandsreise_krankenhaus', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['aperitifs_digestifs'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['bier'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['eier'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['fette'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['fettfreie_zuckerhaltige_produkte'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['fetthaltige_zuckerhaltige_produkte'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['fettige_salzige_produkte'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['fisch_meeresfruechte'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['fruechte_gemuese'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['fruehstueckscerealien'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['gefluegel'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['huelsenfruechte'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['joghurt'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['kaese'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['milch'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], ),
    sa.ForeignKeyConstraint(['rotes_fleisch'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['staerkehaltige_lebensmittel'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['verarbeitetes_fleisch'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['vollwertkost'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['wein'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.ForeignKeyConstraint(['zuckerhaltige_getraenke'], ['ltx_fragebogen_ernaerung_lookup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ltx_fragebogen')
    op.drop_table('ltx_fragebogen_ernaerung_lookup')
    # ### end Alembic commands ###
