"""msg

Revision ID: ff159bd15d21
Revises: 0eae3e8ba621
Create Date: 2025-11-24 11:55:48.756215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff159bd15d21'
down_revision: Union[str, None] = '0eae3e8ba621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paraffinproben',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('uebergeordnete_probenart', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('untergeordnete_probenart', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], name='paraffinproben_ibfk_1'),
    sa.ForeignKeyConstraint(['status'], ['status.id'], name='paraffinproben_ibfk_4'),
    sa.ForeignKeyConstraint(['uebergeordnete_probenart'], ['uebergeordnete_probenart_paraffin.id'], name='paraffinproben_ibfk_2'),
    sa.ForeignKeyConstraint(['untergeordnete_probenart'], ['untergeordnete_probenart_paraffin.id'], name='paraffinproben_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('probenquelle_urin',
    sa.Column('id', mysql.TINYINT(display_width=4), autoincrement=True, nullable=False),
    sa.Column('probenquelle_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('patient',
    sa.Column('sap_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('geschlecht', mysql.TEXT(), nullable=True),
    sa.Column('alter', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('op_diagnose', mysql.TEXT(), nullable=True),
    sa.Column('op_geplant', mysql.TEXT(), nullable=True),
    sa.Column('bemerkung', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('patient_Id_intern'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('status',
    sa.Column('id', mysql.TINYINT(display_width=4), autoincrement=True, nullable=False),
    sa.Column('status_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('uebergeordnete_probenart_paraffin',
    sa.Column('id', mysql.TINYINT(display_width=4), autoincrement=True, nullable=False),
    sa.Column('uebergeordnete_probenart_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('probeninformation',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('probeninformation_text', mysql.TEXT(), nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('untergeordnete_probenart_paraffin',
    sa.Column('id', mysql.TINYINT(display_width=4), autoincrement=True, nullable=False),
    sa.Column('untergeordnete_probenart_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('serumproben',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('probeninformation', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('differenzierungsmerkmal', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('boxnummer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('boxzeile', mysql.TEXT(), nullable=True),
    sa.Column('boxspalte', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['differenzierungsmerkmal'], ['differenzierungsmerkmal_serum.id'], name='serumproben_ibfk_3'),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], name='serumproben_ibfk_1'),
    sa.ForeignKeyConstraint(['probeninformation'], ['probeninformation.id'], name='serumproben_ibfk_2'),
    sa.ForeignKeyConstraint(['status'], ['status.id'], name='serumproben_ibfk_4'),
    sa.PrimaryKeyConstraint('barcode_id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('urinproben',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('probeninformation', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('differenzierungsmerkmal', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('boxnummer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('boxzeile', mysql.TEXT(), nullable=True),
    sa.Column('boxspalte', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['differenzierungsmerkmal'], ['differenzierungsmerkmal_urin.id'], name='urinproben_ibfk_3'),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], name='urinproben_ibfk_1'),
    sa.ForeignKeyConstraint(['probeninformation'], ['probeninformation.id'], name='urinproben_ibfk_2'),
    sa.ForeignKeyConstraint(['status'], ['status.id'], name='urinproben_ibfk_4'),
    sa.PrimaryKeyConstraint('barcode_id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('gewebeproben',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.TEXT(), nullable=True),
    sa.Column('differenzierungsmerkmal', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('probenart', mysql.TEXT(), nullable=True),
    sa.Column('probeninformation', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('abholer', mysql.TEXT(), nullable=True),
    sa.Column('uhrzeit', mysql.TEXT(), nullable=True),
    sa.Column('boxnummer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('boxzeile', mysql.TEXT(), nullable=True),
    sa.Column('boxspalte', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lagerraum', mysql.TEXT(), nullable=True),
    sa.Column('anmerkungen', mysql.TEXT(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('anzahl_statuswechsel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['differenzierungsmerkmal'], ['differenzierungsmerkmal_gewebe.id'], name='gewebeproben_ibfk_2'),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], name='gewebeproben_ibfk_1'),
    sa.ForeignKeyConstraint(['probeninformation'], ['probeninformation.id'], name='gewebeproben_ibfk_3'),
    sa.ForeignKeyConstraint(['status'], ['status.id'], name='gewebeproben_ibfk_4'),
    sa.PrimaryKeyConstraint('barcode_id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('differenzierungsmerkmal_urin',
    sa.Column('id', mysql.TINYINT(display_width=4), autoincrement=True, nullable=False),
    sa.Column('differenzierungsmerkmal_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('differenzierungsmerkmal_serum',
    sa.Column('id', mysql.TINYINT(display_width=4), autoincrement=True, nullable=False),
    sa.Column('differenzierungsmerkmal_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('probenabholer',
    sa.Column('id', mysql.TINYINT(display_width=4), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('vorlaeufigeproben',
    sa.Column('barcode_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('patient_Id_intern', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('probeninformation', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_Id_intern'], ['patient.patient_Id_intern'], name='vorlaeufigeproben_ibfk_1'),
    sa.ForeignKeyConstraint(['probeninformation'], ['probeninformation.id'], name='vorlaeufigeproben_ibfk_2'),
    sa.PrimaryKeyConstraint('barcode_id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('differenzierungsmerkmal_gewebe',
    sa.Column('id', mysql.TINYINT(display_width=4), autoincrement=True, nullable=False),
    sa.Column('differenzierungsmerkmal_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
