export const complicationColumns = [
    { key: "patient_id", label: "Patient ID" },
    { key: "patient_id_old", label: "Patient ID Alt" },
    { key: "created_at", label: "Erstellt am" },
    { key: "duration_of_inpatient_stay_d", label: "Dauer des Krankenhausaufenthalts (Tage)" },
    { key: "duration_intermediate_care_d", label: "Dauer der Intermediate Care (Tage)" },
    { key: "duration_intensive_care_station_d", label: "Dauer der Intensivstation (Tage)" },
    { key: "ventilation_duration_h", label: "Dauer der Beatmung (Stunden)" },
    { key: "noninvasive_ventilation_duration_h", label: "Dauer der nichtinvasiven Beatmung (Stunden)" },
    { key: "complication_free_progression", label: "Komplikationsfreier Verlauf" },
    { key: "liver_failure", label: "Leberversagen" },
    { key: "urinary_retention", label: "Harnverhalt" },
    { key: "ileus", label: "Ileus" },
    { key: "cholascos", label: "Cholascos" },
    { key: "cholangitis", label: "Cholangitis" },
    { key: "reintubation", label: "Reintubation" },
    { key: "pneumonia", label: "Pneumonie" },
    { key: "thrombosis", label: "Thrombose" },
    { key: "embolism", label: "Embolie" },
    { key: "postoperative_bleeding", label: "Postoperative Blutung" },
    { key: "pleural_effusion", label: "Pleuraerguss" },
    { key: "burst_abdomen", label: "Bauchdeckenruptur" },
    { key: "liver_abscess", label: "Leberabszess" },
    { key: "intraabdomineller_Abszess", label: "Intraabdomineller Abszess" },
    { key: "biliom", label: "Biliom" },
    { key: "decubitus", label: "Dekubitus" },
    { key: "decubitus_score", label: "Dekubitus Score" },
    { key: "secondary_wound_healing", label: "Sekundäre Wundheilung" },
    { key: "multi_organ_failure", label: "Multiorganversagen" },
    { key: "anastomotic_insufficiency", label: "Anastomoseninsuffizienz" },
    { key: "anastomotic_insufficiency_type", label: "Anastomoseninsuffizienz Typ" },
    { key: "other_complications", label: "Andere Komplikationen" },
    { key: "other_complications_1", label: "Andere Komplikationen 1" },
    { key: "other_complications_2", label: "Andere Komplikationen 2" },
    { key: "other_complications_3", label: "Andere Komplikationen 3" },
    { key: "other_complications_4", label: "Andere Komplikationen 4" },
    { key: "other_complications_5", label: "Andere Komplikationen 5" },
    { key: "other_complications_6", label: "Andere Komplikationen 6" },
    { key: "thoracic_drainage_for_effusion", label: "Thoraxdrainage für Erguss" },
    { key: "simplified_acute_physiology_score_average", label: "SAPS (Durchschnitt)" },
    { key: "drainage_complication", label: "Drainage Komplikation" },
    { key: "drainage_complication_text", label: "Drainage Komplikation Text" },
    { key: "endoscopy", label: "Endoskopie" },
    { key: "endoscopic_retrograde_cholangiopancreatography", label: "ERCP" },
    { key: "endoscopy_text", label: "Endoskopie Text" },
    { key: "haemodialysis", label: "Hämodialyse" },
    { key: "haemodialysis_h", label: "Hämodialyse (Stunden)" },
    { key: "mutation_adjusted_risk_score", label: "Mutationsangepasster Risikoscore" },
    { key: "mutation_adjusted_risk_score_h", label: "Mutationsangepasster Risikoscore (Stunden)" },
    { key: "interventional_drainage", label: "Interventionelle Drainage" },
    { key: "re_operation", label: "Reoperation" },
    { key: "clavien_dindo", label: "Clavien-Dindo" },
    { key: "kidney_insufficiency", label: "Niereninsuffizienz" },
    { key: "readmission_to_clinic", label: "Wiederaufnahme in die Klinik" },
    { key: "readmission_to_clinic_date", label: "Datum der Wiederaufnahme" },
    { key: "other_complication_management", label: "Andere Komplikationsbehandlung" },
    { key: "other_complication_management_text", label: "Andere Komplikationsbehandlung Text" },
    { key: "relocation_intensive_care_unit", label: "Verlegung auf die Intensivstation" },
    { key: "relocation_intermediate_care_unit", label: "Verlegung auf die Intermediate Care" },
    { key: "acute_coronary_syndrome", label: "Akutes Koronarsyndrom" },
    { key: "sepsis", label: "Sepsis" },
    { key: "systemic_inflammatory_response_syndrome", label: "SIRS" },
    { key: "circulatory_instability", label: "Kreislaufinstabilität" },
    { key: "reanimation", label: "Reanimation" },
    { key: "duration_reanimation_min", label: "Dauer der Reanimation (Minuten)" },
    { key: "respiratory_failure", label: "Atemversagen" },
    { key: "hollow_organ_perforation", label: "Hohlorganperforation" },
    { key: "which_organ_is_perforated", label: "Welches Organ ist perforiert" },
    { key: "intestinal_passage_disorder", label: "Darmpassagestörung" },
    { key: "ascites_postoperative", label: "Aszites postoperativ" },
    { key: "pancreatitis_postoperative", label: "Pankreatitis postoperativ" },
    { key: "urinary_tract_infection_postoperative", label: "Harnwegsinfektion postoperativ" },
    { key: "delirium", label: "Delirium" },
    { key: "delirium_type", label: "Delirium Typ" },
    { key: "cholecystitis", label: "Cholezystitis" },
    { key: "pancreatic_fistula", label: "Pankreasfistel" },
    { key: "internal_hernia", label: "Innere Hernie" },
    { key: "pleural_empyema", label: "Pleuraempyem" }
];

