export type LaboratoryData = {
    id: number;
    patient_id: number;
    patient_id_old: number;
    created_at: null | string;
    date_laboratory_analysis: null | string;
    ASAT_μmol_per_l: null | number;
    ALAT_μmol_per_l: null | number;
    AP_μmol_per_l: null | number;
    GGT_μmol_per_l: null | number;
    Lipase_μmol_per_l: null | number;
    Kreatinin_μmol_per_l: null | number;
    Bilirubin_μmol_per_l: null | number;
    Quickk_percent: null | number;
    INR: null | number;
    Cholinesterase_μmol_per_l: null | number;
    Natrium_mmol_per_l: null | number;
    Hämoglobin_mmol_per_l: null | number;
    Leukozyten_Gpt_per_l: null | number;
    CRP_mg_per_l: null | number;
    PCT_ng_ml: null | number;
    Albumin_g_per_l: null | number;
    Harnstoff_mmol_per_l: null | number;
    GFR_ml_per_min: null | number;
    MDRD_ml_per_min: null | number;
    TSH_mU_per_l: null | number;
    HbA1c_percent: null | number;
    s_ColLineage: null | string;
    s_Generation: null | string;
    s_GUID: null | string;
    s_Lineage: null | number;
};