export const laboratoryDataColumns = [
    { key: "patient_id", label: "Patient ID" },
    { key: "ASAT_μmol_per_l", label: "ASAT (μmol/l)" },
    { key: "ALAT_μmol_per_l", label: "ALAT (μmol/l)" },
    { key: "AP_μmol_per_l", label: "AP (μmol/l)" },
    { key: "GGT_μmol_per_l", label: "GGT (μmol/l)" },
    { key: "Lipase_μmol_per_l", label: "Lipase (μmol/l)" },
    { key: "Kreatinin_μmol_per_l", label: "Kreatinin (μmol/l)" },
    { key: "Bilirubin_μmol_per_l", label: "Bilirubin (μmol/l)" },
    { key: "Quickk_percent", label: "Quickk (%)" },
    { key: "INR", label: "INR" },
    { key: "Cholinesterase_μmol_per_l", label: "Cholinesterase (μmol/l)" },
    { key: "Natrium_mmol_per_l", label: "Natrium (mmol/l)" },
    { key: "Hämoglobin_mmol_per_l", label: "Hämoglobin (mmol/l)" },
    { key: "Leukozyten_Gpt_per_l", label: "Leukozyten (Gpt/l)" },
    { key: "CRP_mg_per_l", label: "CRP (mg/l)" },
    { key: "PCT_ng_ml", label: "PCT (ng/ml)" },
    { key: "Albumin_g_per_l", label: "Albumin (g/l)" },
    { key: "Harnstoff_mmol_per_l", label: "Harnstoff (mmol/l)" },
    { key: "GFR_ml_per_min", label: "GFR (ml/min)" },
    { key: "MDRD_ml_per_min", label: "MDRD (ml/min)" },
    { key: "TSH_mU_per_l", label: "TSH (mU/l)" },
    { key: "HbA1c_percent", label: "HbA1c (%)" },
    { key: "s_ColLineage", label: "s_ColLineage" },
    { key: "s_Generation", label: "s_Generation" },
    { key: "s_GUID", label: "s_GUID" },
    { key: "s_Lineage", label: "s_Lineage" }
];