export const medicalHistoryColumns = [
    { key: "patient_id", label: "Patient ID" },
    { key: "patient_id_old", label: "Patient ID Alt" },
    { key: "created_at", label: "Erstellt am" },
    { key: "body_size_cm", label: "Körpergröße (cm)" },
    { key: "weight_kg", label: "Gewicht (kg)" },
    { key: "body_mass_index", label: "Body Mass Index" },
    { key: "family_history_neoplastic_disease", label: "Familienanamnese neoplastische Erkrankung" },
    { key: "family_history_neoplastic_disease_text", label: "Familienanamnese neoplastische Erkrankung Text" },
    { key: "number_of_relatives_first_degree", label: "Anzahl der Verwandten ersten Grades" },
    { key: "previous_tumour", label: "Vorheriger Tumor" },
    { key: "previous_tumour_text", label: "Vorheriger Tumor Text" },
    { key: "previous_secondary_tumour", label: "Vorheriger Sekundärtumor" },
    { key: "previous_secondary_tumour_text", label: "Vorheriger Sekundärtumor Text" },
    { key: "pre_existing_disease_immunological", label: "Vorhandene immunologische Erkrankung" },
    { key: "pre_existing_disease_immunological_text", label: "Vorhandene immunologische Erkrankung Text" },
    { key: "pre_existing_liver_disease", label: "Vorhandene Lebererkrankung" },
    { key: "hepatitis_B", label: "Hepatitis B" },
    { key: "hepatitis_C", label: "Hepatitis C" },
    { key: "hepatitis_D", label: "Hepatitis D" },
    { key: "ethyltoxic", label: "Äthyltoxisch" },
    { key: "child_stadium", label: "Child-Stadium" },
    { key: "other_pre_existing_diseases", label: "Andere vorhandene Erkrankungen" },
    { key: "other_liver_disease", label: "Andere Lebererkrankung" },
    { key: "other_pre_existing_diseases_1", label: "Andere vorhandene Erkrankungen 1" },
    { key: "other_pre_existing_diseases_2", label: "Andere vorhandene Erkrankungen 2" },
    { key: "other_pre_existing_diseases_3", label: "Andere vorhandene Erkrankungen 3" },
    { key: "other_pre_existing_diseases_4", label: "Andere vorhandene Erkrankungen 4" },
    { key: "other_pre_existing_diseases_5", label: "Andere vorhandene Erkrankungen 5" },
    { key: "reduced_general_state", label: "Reduzierter Allgemeinzustand" },
    { key: "loss_of_appetite", label: "Appetitlosigkeit" },
    { key: "nausea_vomiting", label: "Übelkeit und Erbrechen" },
    { key: "abdominal_pain", label: "Bauchschmerzen" },
    { key: "back_pain", label: "Rückenschmerzen" },
    { key: "dyspnoea", label: "Dyspnoe" },
    { key: "diarrhoea", label: "Durchfall" },
    { key: "constipation", label: "Verstopfung" },
    { key: "nocturia", label: "Nykturie" },
    { key: "weight_loss", label: "Gewichtsverlust" },
    { key: "fever", label: "Fieber" },
    { key: "night_sweat", label: "Nachtschweiß" },
    { key: "hepatomegaly_splenomegaly", label: "Hepatomegalie/Splenomegalie" },
    { key: "ascites", label: "Aszites" },
    { key: "ascites_severity", label: "Schweregrad des Aszites" },
    { key: "icterus", label: "Ikterus" },
    { key: "oedema", label: "Ödem" },
    { key: "further_symptoms", label: "Weitere Symptome" },
    { key: "further_symptoms_text", label: "Weitere Symptome Text" },
    { key: "diagnosis_date_primary_tumour", label: "Diagnosedatum Primärtumor" },
    { key: "diagnosis_date_metastasis", label: "Diagnosedatum Metastase" },
    { key: "type_primary_metastasis", label: "Typ Primärmetastase" },
    { key: "localisation_of_the_metastasis", label: "Lokalisation der Metastase" },
    { key: "first_haemodialysis", label: "Erste Hämodialyse" },
    { key: "diabetes_type", label: "Diabetes Typ" },
    { key: "nicotine_abuse", label: "Nikotinkonsum" },
    { key: "nicotine_amount_py", label: "Nikotinmenge (Pack-Years)" },
    { key: "alcohol_abuse", label: "Alkoholkonsum" },
    { key: "pulmonary_pre_existing_diseases", label: "Vorhandene Lungenerkrankungen" },
    { key: "pulmonary_pre_existing_diseases_text", label: "Vorhandene Lungenerkrankungen Text" },
    { key: "arterial_hypertension", label: "Arterielle Hypertonie" },
    { key: "charlson_comorbidity_index", label: "Charlson-Komorbiditätsindex" },
    { key: "cardiac_event", label: "Herzereignis" },
    { key: "peripheral_artery_disease", label: "Periphere Arterienerkrankung" },
    { key: "cerebrovascular_event", label: "Zerebrovaskuläres Ereignis" },
    { key: "dementia", label: "Demenz" },
    { key: "chronic_obstructive_pulmonary_disease", label: "COPD" },
    { key: "connective_tissue_disease", label: "Bindegewebserkrankung" },
    { key: "hemiplegia", label: "Hemiplegie" },
    { key: "previous_operations", label: "Vorherige Operationen" },
    { key: "chronic_pancreatitis", label: "Chronische Pankreatitis" },
    { key: "inflammatory_bowel_disease", label: "Entzündliche Darmerkrankung" },
    { key: "dysphagia", label: "Dysphagie" },
    { key: "chronic_renal_insufficiency_stage", label: "Stadium der chronischen Niereninsuffizienz" },
    { key: "pre_existing_thyroid_disease", label: "Vorhandene Schilddrüsenerkrankung" },
    { key: "arthrosis", label: "Arthrose" },
    { key: "osteoporosis", label: "Osteoporose" },
    { key: "gastrala_ulcera", label: "Gastrale Ulcera" },
    { key: "dermal_ulcera", label: "Dermale Ulcera" },
    { key: "deep_leg_vein_thrombosis", label: "Tiefe Beinvenenthrombose" },
    { key: "mental_pre_existing_diseases", label: "Vorhandene psychische Erkrankungen" },
    { key: "cardiac_event_text", label: "Herzereignis Text" },
    { key: "acute_pancreatitis", label: "Akute Pankreatitis" },
    { key: "cholestasis", label: "Cholestase" },
    { key: "cholangitis", label: "Cholangitis" },
    { key: "pleural_effusion", label: "Pleuraerguss" },
    { key: "coronary_heart_disease", label: "Koronare Herzkrankheit" },
    { key: "cardiac_arrhythmia", label: "Herzrhythmusstörung" },
    { key: "cardiac_arrhythmia_text", label: "Herzrhythmusstörung Text" },
    { key: "congestive_heart_failure", label: "Herzinsuffizienz" },
    { key: "lipid_metabolism_disorders", label: "Lipidstoffwechselstörung" },
    { key: "neurological_pre_existing_disease", label: "Vorhandene neurologische Erkrankung" },
    { key: "neurological_pre_existing_disease_text", label: "Vorhandene neurologische Erkrankung Text" },
    { key: "hiatal_hernia", label: "Hiatushernie" },
    { key: "diverticulosis", label: "Divertikulose" },
    { key: "cholecystolithiasis", label: "Cholezystolithiasis" },
    { key: "hyperuricaemia_gout", label: "Hyperurikämie/Gicht" },
    { key: "gastritis", label: "Gastritis" }
];
