export const serumprobenDataColumns = [
    { key: "barcode_id", label: "Barcode ID" },
    { key: "patient_Id_intern", label: "Patienten ID (intern)" },
    { key: "probenart", label: "Probenart" },
    { key: "probeninformation", label: "Probeninformation" },
    { key: "differenzierungsmerkmal", label: "Differenzierungsmerkmal" },
    { key: "created_at", label: "Erstellungsdatum" },
    { key: "uhrzeit", label: "Probe erhalten (Uhrzeit)" },
    { key: "boxnummer", label: "Boxname (Boxnummer)" },
    { key: "boxzeile", label: "Boxzeile" },
    { key: "boxspalte", label: "Boxspalte" },
    { key: "lagerraum", label: "Lagerraum" },
    { key: "abholer", label: "Abholer:In" },
    { key: "anmerkungen", label: "Anmerkungen"},
    { key: "status", label: "Probenstatus" },
];
